version: "3"
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: "local_postgres"
    environment:
      POSTGRES_PASSWORD: "password:${POSTGRES_PASSWORD}"
    ports:
      - "54320:${POSTGRES_PORT}"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: {}
