version: "3"
services:
  db:
    image: "postgres:14"
    container_name: "local_postgres"
    environment:
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
